gcc -Wall -pthread bin/calculC.o src/noeud.c -o bin/noeud
gcc -Wall -pthread bin/calculC.o src/messageSender.c -o bin/sender

gcc -Wall -pthread bin/calculC.o exemple/racine.c -o exemple/racine
gcc -Wall -pthread bin/calculC.o exemple/noeud.c -o exemple/noeud

gcc -Wall -pthread bin/calculC.o exemple2/racine.c -o exemple2/racine
gcc -Wall -pthread bin/calculC.o exemple2/noeud.c -o exemple2/noeud