import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

const routes: Routes = [{path: "/", component: AppComponent},{path: "/NodeStyle", component: NodeStyleComponent},{path: "/GanttStyle", component: GanttStyleComponent},{path: "/SplitTaskSample", component: SplitTaskSampleComponent},{path: "/CustomizedTable", component: CustomizedTableComponent},{path: "/ExternalPropertyBinding", component: ExternalPropertyBindingComponent},{path: "/FlatPerformanceCheck", component: FlatPerformanceCheckComponent},{path: "/HighlightingTasks", component: HighlightingTasksComponent},{path: "/CustomZooming", component: CustomZoomingComponent},{path: "/CustomMetroStyle", component: CustomMetroStyleComponent},{path: "/Predecessors", component: PredecessorsComponent},{path: "/HierarchyPerformanceCheck", component: HierarchyPerformanceCheckComponent},{path: "/CustomNumericSchedule", component: CustomNumericScheduleComponent},{path: "/CalendarCustomization", component: CalendarCustomizationComponent},{path: "/ResourceView", component: ResourceViewComponent},{path: "/EssentialGantt", component: EssentialGanttComponent},{path: "/ProjectScheduler", component: ProjectSchedulerComponent},{path: "/StatisticsWindow", component: StatisticsWindowComponent},{path: "/ImportExportDemo", component: ImportExportDemoComponent},{path: "/CriticalPath", component: CriticalPathComponent},{path: "/CustomizedScheduleAppearance", component: CustomizedScheduleAppearanceComponent},{path: "/BaselineTableView", component: BaselineTableViewComponent},{path: "/ExportToImage", component: ExportToImageComponent},{path: "/ResourceNameCustomization", component: ResourceNameCustomizationComponent},{path: "/CustomDateTimeSchedule", component: CustomDateTimeScheduleComponent},{path: "/BindingTaskDetails", component: BindingTaskDetailsComponent},{path: "/CustomToolTip", component: CustomToolTipComponent},{path: "/BuiltinZooming", component: BuiltinZoomingComponent},{path: "/CustomNodeStyle", component: CustomNodeStyleComponent},{path: "/GanttStyleProperties", component: GanttStylePropertiesComponent},{path: "/GanttStripLine", component: GanttStripLineComponent},{path: "/ProjectStatistics", component: ProjectStatisticsComponent},];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
